# Site settings
title: Saltvedt Tech
email: jan.ove@saltvedt.tech
description: > # this means to ignore newlines until "baseurl:"
  A blog with a focus on Jan Ove Saltvedt's personal projects. If I bother documenting some of my builds, it may as well be shared with the rest of the world. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://saltvedt.tech" # the base hostname & protocol for your site
twitter_username: SaltvedtTech
github_username:  JanOveSaltvedt

# Build settings
markdown: kramdown
