# Site settings
title: Saltvedt Tech
email: jan.ove@saltvedt.tech
description: > # this means to ignore newlines until "baseurl:"
  Jan Ove Saltvedt's personal blog that focuses on documenting his maker projects.
  The projects includes the creation of custom engineered  electrical hardware, software and mechanics.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://saltvedt.tech" # the base hostname & protocol for your site
twitter_username: SaltvedtTech
github_username:  JanOveSaltvedt

# Build settings
markdown: kramdown
